### ISSUE TITLE
Access to the API without authing with Unraid

### ISSUE THREAD

**Issue by acateon** [CyanLabs/jsonapi-unraid#2]
Not possible (to my knowledge) to extract API data without being authed with Unraid.
As of now Home Assistant will be blocked when issuing a GET request as a json sensor.

**Comment by fma965** [comment]
Yes this is a limitation of unraid not much i can do about that, add basic auth to home assistant config 

```
  - platform: rest
    resource: "http://192.168.1.3:965/plugins/jsonapi/api.php?file=XXX.ini"
    username: root
    password: !secret unraid_password
    authentication: basic
    value_template: '{{ value_json.XXXX }}'
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
```
